### ISSUE TITLE
Orders panel UI Amends

### ISSUE THREAD

**Issue by foxleigh81** [serge-web/serge#306]
- [ ]  for red coastal radar, the "no missiles" information should not be associated to the name but a mention below similar to "x turns planned". 
- [x] the icon to minimize and maximize should show the action rather than the current state: similar to managing a list (maybe I should move the icon to the left to make this more clear) 
- [x] on hover on the icon and platform name in the orders panel, the condition should appear (Full capability, etc) as it does when hovering over a marker on the map (but no need for the name as it is already there)
- [x] panel title should be a header: font size, small capitals
- [x] for white, it would be useful to open and collapse each force separately
- [x] I like the choice of the checkmark icon. I would align them on the right, and add gray checkmarks for platforms where orders are pending.  (see below)

![Screenshot_2020-02-04 Figma(1)](https://user-images.githubusercontent.com/151028/73836920-41da8680-4808-11ea-89c7-4496e21527e1.png)

**Comment by foxleigh81** [comment]
@clenoble Here are the amends, I've not yet done the first one as I'm awaiting feedback from @IanMayo as to how to handle it from a data perspective.

## Changes to White POV
![2020-02-05 16 30 01](https://user-images.githubusercontent.com/151028/73861446-ee326200-4834-11ea-9f57-1ed676d37b5e.gif)

## Player orders remain pretty much the same
![Screenshot 2020-02-05 16 30 57](https://user-images.githubusercontent.com/151028/73861547-1621c580-4835-11ea-9979-a2d19e058f7d.png)

**Comment by foxleigh81** [comment]
Here is the deployment: https://serge-review-fix-297-ad-dui7tm.herokuapp.com/

**Comment by clenoble** [comment]
@foxleigh81 Thanks for the URL. There's a bug on my computer: the list goes beyond the panel (see attached screenshot)

In white role, when clicking on individual platforms and accepting the planned route, the status was not updated in the SOW panel. The green checkmarks appeared only after I clicked on the "Accept remaining xx" buttons. (It works when planning a route as blue)

There is no grey checkmarks next to platforms that still need to be reviewed (or plan a new route),

The mini/maxi icon for the panel is in the top right corner as it was initially. I placed it on the left in the last design, but don't mind keeping it in this corner. 

![Screenshot_2020-02-05 Serge](https://user-images.githubusercontent.com/22282418/73863401-4c187700-4840-11ea-83af-30364650a02b.png)
![Screenshot_2020-02-05 Serge(1)](https://user-images.githubusercontent.com/22282418/73863411-50449480-4840-11ea-975f-b9b5b8885e70.png)

**Comment by clenoble** [comment]
I realize that in the screenshot above it seems like the map is on a layer on top of the panel instead of being below. I move the map and it went back to be in the background. I can't manage to reproduce how it came to be on top.

**Comment by foxleigh81** [comment]
@clenoble I can't actually reproduce that scrolling bug. I did have that problem earlier but it was something I fixed, can you try running clearing your cache and trying again?

Looking at the code, the green checkboxes are there to indicate if a message has been received for that asset. So I want to have a word with @IanMayo about that first to see what logic I can change for it before I make it add the grey checkboxes.

> In white role, when clicking on individual platforms and accepting the planned route, the status was not updated in the SOW panel. The green checkmarks appeared only after I clicked on the "Accept remaining xx" buttons. (It works when planning a route as blue)

I've only been dealing with cosmetic issues here, this may be something @IanMayo is planning to tackle himself. If not I'm sure I'll get a ticket for it soon enough :)

**Comment by clenoble** [comment]
@foxleigh81 I still have the same issue with the SOW panel on 2 different browsers, Chrome and Firefox. I never used Chrome before to test so there was no cache. 
![SOW-panel-bug](https://user-images.githubusercontent.com/22282418/73923453-2e442400-48cb-11ea-960c-1acf3e5f8166.png)

**Comment by IanMayo** [comment]
Oh dear @clenoble - could you provide the steps you take to produce the error?

**Comment by clenoble** [comment]
I only logged in as white in IMWARC-initialized: the list of platform is extended by default, and if I scroll down that's what I see.

**Comment by foxleigh81** [comment]
Ah, you are on Windows. I'm currently on Mac but I'll be doing some platform testing later today when I try to fix a mobile issue so I'll test this on Windows too. Hopefully, I'll be able to reproduce it there. Windows handles scrollbars differently to Mac so it's probably related to that.

**Comment by IanMayo** [comment]
We were testing on a range of PCs on Tuesday (including 3 with wall-mounted touch monitors), but none had that issue.  (fully acknowledging that @clenoble clearly has it :-) )

**Comment by foxleigh81** [comment]
@clenoble is there a chance you are zoomed in? That can often cause display issues.

**Comment by clenoble** [comment]
@foxleigh81 No, I'm at 100%. I have Windows 10 updated to the last version. Same for Chrome and Firefox. 
@IanMayo Did you use Chrome, Edge or IE to test on the PC and wall-mounted screens?

**Comment by foxleigh81** [comment]
Ian managed to reproduce it and showed me how to. I've now fixed it and will push the fix up soon :)
